name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Shared.sln'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Prevent a shallow clone to allow git describe --tags

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    # .Net 8 update     
    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
         dotnet-version: |
           8.0.x
         include-prerelease: false

     - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
